AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  WalletFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: WalletFunction
      Handler: main
      Runtime: go1.x
      CodeUri: cmd/handler/
      MemorySize: 128
      Timeout: 10
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonSSMFullAccess
      Environment:
        Variables:
          DYNAMO_TABLE: "wallets-development"
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /wallet
            Method: post

Outputs:
  ApiGatewayInvokeURL:
    Description: "API Gateway endpoint URL"
    Value: !Sub "http://localhost:3000/wallet"
